datasets:
  3d_caption:
    data_type: "pointcloud"
    build_info:
      annotations:
        train:
          # storage: "/home/tdt/3DLLM/data_process/ZN-train4.json"
          # storage: "/data4/tdt/structure3d/ZN-train_text.json"
          storage: "/data3/lyz/merge/ZN-merge_train.json"
          # storage:  "/data3/rmq/points_text_datasets/S3DIS/text_embed/ZN-s3dis_text_absolute.json"            # 这里放一个 json 文件，里面保存点云路径以及相对应的文本
          # storage: "/data3/lyz/merge/ZN-merge_val.json"
        # test:
        #   storage: "xxxxx.json"
        val: 
          # storage: "/home/tdt/ZN-s3dis_text_absolute.json"
          storage: "/data3/lyz/merge/ZN-merge_val.json"
          # storage: "/data4/tdt/structure3d/ZN-train_text.json"
          # storage: "/home/tdt/3DLLM/data_process/ZN-val4.json"
