# Copyright (c) 2022, salesforce.com, inc.
# All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
# For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

model:
  arch: blip2_llama
  model_type: llama_chinese
  load_finetuned: False
  use_grad_checkpoint: True
  freeze_vit: False

datasets:
  3d_caption:                     # 数据集的名字, 对应于 Builder, 然后对应于 config/datasets/point_cloud/xxxx.json
    vis_processor:
      train:
        name: "cloud_train"
        max_size: 10000
      eval:                       # eval 等价于 val + test
        name: "cloud_test"
        max_size: 10000
    text_processor:
      train:
        name: "chinese_caption"   
        max_words: 50
      eval:
        name: "chinese_caption"
        max_words: 50

run:
  task: 3d_captioning
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 0
  warmup_lr: 1e-8
  warmup_steps: 1000
  weight_decay: 0.05
  max_epoch: 5
  batch_size_train: 16
  batch_size_eval: 8
  num_workers: 4
  accum_grad_iters: 1

  max_len: 30
  min_len: 8
  num_beams: 5

  seed: 42
  output_dir: "output/BLIP2/Caption"

  amp: True
  resume_ckpt_path: null

  evaluate: True              # 设置为只验证, 不训练
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True